default['anodot']['token'] = "<YOUR ANODOT TOKEN>"
default['anodot']['loglevel'] = "error"
default['anodot']['showStats'] = false
default['anodot']['sendStats'] = true
default['anodot']['plainPort'] = 2003
default['anodot']['picklePort'] = 2004
default['anodot']['flushInterval'] = 5000
default['anodot']['metricFilter'] = ""
default['anodot']['metricRewrite'] = []
default['anodot']['version'] = nil
